#!/usr/bin/env zsh

brewcaskinstall "HyperTerm"

# browser
brewcaskinstall "firefoxdeveloperedition"

## Ssh
setupsh-recipe ssh

## Zsh completion
brewinstall zsh-completions

## Some utilities
brewcaskinstall "Flux"
openifnot "Flux"

## Development
setupsh-recipe git
brewcaskinstall atom

### Node
setupsh-recipe nvm
nvm alias default 5
nvm install default --reinstall-packages-from=node
npm config set progress false
npm config set cache-min 20000 # 6 hours (60*60*6)

if [ "$FIRSTRUN" = "true" ]; then osx-refresh; fi;

# safer than rm
npmig trash-cli

brewcaskinstall "WebTorrent"
brewcaskinstall "VLC"

# apps
brewcaskinstall "AppCleaner"
openifnot "AppCleaner"

##
# Stuff that are slow to download
# or that require human interaction
##

##
# Less important stuff
#
# install later (not during the first run)
##
if [ "$FIRSTRUN" = "" ]
then
  # messaging
  brewcaskinstall "Slack"
  brewcaskinstall "Discord"
  brewcaskinstall "Skype"
  brewcaskinstall "WhatsApp"

  # social
  brewcaskinstall "Twitter"

  # MORE BROWSER
  brewcaskinstall "Firefox"
  brewcaskinstall "Google Chrome"

  # vm and shit
  # brewcaskinstall "VirtualBox"
  # Android development
  # might be required http://software.intel.com/en-us/android/articles/intel-hardware-accelerated-execution-manager
  # brewinstall android-sdk
  # brewcaskinstall genymotion

  # meta
  # https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask
  # brewinstall vitorgalvao/tiny-scripts/cask-repair

  # multimedia
  brewcaskinstall "Spotify"
fi
